# Curated Wikipedia Title Mappings for NCERT Class 9-12 Physics and Mathematics

FIXES = {
    # Class 9 Physics
    ("physics", 9, "Motion", "Uniform and non-uniform acceleration"): "Acceleration",
    ("physics", 9, "Motion", "Equations of motion by graphical method"): "Equations of motion",
    ("physics", 9, "Motion", "Interpreting position-time and velocity-time graphs"): "Equations of motion",
    ("physics", 9, "Motion", "Distance and displacement"): "Displacement (vector)",
    ("physics", 9, "Work and Energy", "Power and commercial unit of energy"): "Power (physics)",

    # Class 9 Math
    ("math", 9, "Polynomials", "Algebraic identities"): "Polynomial identity",
    ("math", 9, "Polynomials", "Remainder and factor theorem"): "Polynomial remainder theorem",
    ("math", 9, "Coordinate Geometry", "Distance between two points"): "Euclidean distance",
    ("math", 9, "Linear Equations in Two Variables", "Equations of lines parallel to axes"): "Linear equation",
    ("math", 9, "Circles", "Equal chords and distances from centre"): "Chord (geometry)",
    ("math", 9, "Heron's Formula and Mensuration", "Volume of cones, spheres, hemispheres"): "Sphere",
    ("math", 9, "Statistics and Probability", "Mean, median, mode of grouped data"): "Central tendency",
    ("math", 9, "Statistics and Probability", "Graphical representation of data"): "Histogram",
    ("math", 9, "Algebraic Identities", "Standard identities: (a+b)^2, (a-b)^2, a^2-b^2"): "Difference of two squares",
    ("math", 9, "Algebraic Identities", "Identities for (a+b)^3 and (a-b)^3"): "Binomial theorem",
    ("math", 9, "Algebraic Identities", "Applications in simplifying expressions"): "Expression (mathematics)",
    ("math", 9, "Sequences and Progressions", "Finding the nth term and predicting patterns"): "Arithmetic progression",

    # Class 10 Physics
    ("physics", 10, "Light - Reflection and Refraction", "Laws of reflection and spherical mirrors"): "Reflection (physics)",
    ("physics", 10, "Human Eye and Colourful World", "Defects of vision and correction"): "Refractive error",
    ("physics", 10, "Human Eye and Colourful World", "Dispersion and scattering of light"): "Dispersion (optics)",
    ("physics", 10, "Electricity", "Electric current and potential difference"): "Electric potential",
    ("physics", 10, "Electricity", "Heating effect of current and electric power"): "Joule heating",
    ("physics", 10, "Magnetic Effects of Electric Current", "Magnetic field due to a current-carrying conductor"): "Biot–Savart law",
    ("physics", 10, "Magnetic Effects of Electric Current", "Force on a current-carrying conductor"): "Lorentz force",
    ("physics", 10, "Magnetic Effects of Electric Current", "Electric motor principle"): "Electric motor",
    ("physics", 10, "Sources of Energy", "Solar energy and nuclear energy basics"): "Solar energy",

    # Class 10 Math
    ("math", 10, "Real Numbers", "Irrationality proofs"): "Square root of 2",
    ("math", 10, "Polynomials", "Relationship between zeroes and coefficients"): "Vieta's formulas",
    ("math", 10, "Polynomials", "Division algorithm for polynomials"): "Polynomial long division",
    ("math", 10, "Pair of Linear Equations in Two Variables", "Graphical method of solution"): "System of linear equations",
    ("math", 10, "Pair of Linear Equations in Two Variables", "Substitution and elimination methods"): "System of linear equations",
    ("math", 10, "Arithmetic Progressions", "nth term of an AP"): "Arithmetic progression",
    ("math", 10, "Arithmetic Progressions", "Sum of first n terms"): "Arithmetic progression",
    ("math", 10, "Arithmetic Progressions", "Applications of AP"): "Arithmetic progression",
    ("math", 10, "Introduction to Trigonometry", "Values at standard angles"): "Exact trigonometric values",
    ("math", 10, "Applications of Trigonometry", "Heights and distances problems"): "Trigonometry",
    ("math", 10, "Circles", "Number of tangents from a point"): "Tangent lines to circles",
    ("math", 10, "Mensuration and Statistics", "Areas related to circles (sectors, segments)"): "Circular sector",
    ("math", 10, "Mensuration and Statistics", "Surface areas and volumes of combined solids"): "Surface area",
    ("math", 10, "Mensuration and Statistics", "Mean, median, mode of grouped data"): "Central tendency",
    ("math", 10, "Mensuration and Statistics", "Probability basics"): "Probability",

    # Class 11 Physics
    ("physics", 11, "Laws of Motion", "Circular motion dynamics and banking of roads"): "Banked turn",
    ("physics", 11, "Laws of Motion", "Pseudo force and non-inertial frames"): "Fictitious force",
    ("physics", 11, "Work, Energy and Power", "Conservative and non-conservative forces"): "Conservative force",
    ("physics", 11, "System of Particles and Rotational Motion", "Rolling motion"): "Rolling",
    ("physics", 11, "Gravitation", "Orbital velocity and satellites"): "Orbital speed",
    ("physics", 11, "Thermal Properties and Thermodynamics", "Thermal expansion and calorimetry"): "Thermal expansion",
    ("physics", 11, "Thermal Properties and Thermodynamics", "Thermodynamic processes (isothermal, adiabatic)"): "Thermodynamic process",
    ("physics", 11, "Thermal Properties and Thermodynamics", "Second law and heat engines"): "Second law of thermodynamics",
    ("physics", 11, "Oscillations and Waves", "Beats and Doppler effect"): "Doppler effect",

    # Class 11 Math
    ("math", 11, "Sets, Relations and Functions", "Types of relations"): "Binary relation",
    ("math", 11, "Trigonometric Functions", "Graphs of trigonometric functions"): "Trigonometric functions",
    ("math", 11, "Trigonometric Functions", "Trigonometric equations"): "Trigonometric functions",
    ("math", 11, "Sequences and Series", "Sum to n terms of special series"): "Series (mathematics)",
    ("math", 11, "Straight Lines and Conic Sections", "Slope and equations of a line"): "Slope",
    ("math", 11, "Limits and Derivatives", "Algebra of limits"): "Limit of a function",
    ("math", 11, "Limits and Derivatives", "Standard limits"): "Limit of a function",
    ("math", 11, "Limits and Derivatives", "Derivative from first principles"): "Derivative",
    ("math", 11, "Limits and Derivatives", "Derivatives of standard functions"): "Differentiation rules",
    ("math", 11, "Linear Inequalities", "Solving linear inequalities in one variable"): "Linear inequality",
    ("math", 11, "Linear Inequalities", "Graphical solution of linear inequalities in two variables"): "Linear inequality",
    ("math", 11, "Linear Inequalities", "Solving a system of linear inequalities"): "Linear inequality",
    ("math", 11, "Introduction to Three Dimensional Geometry", "Distance between two points in space"): "Euclidean distance",
    ("math", 11, "Introduction to Three Dimensional Geometry", "Section formula in 3D"): "Section formula",
    ("math", 11, "Statistics", "Measures of dispersion: range and mean deviation"): "Statistical dispersion",
    ("math", 11, "Statistics", "Variance and standard deviation"): "Standard deviation",
    ("math", 11, "Statistics", "Analysis of frequency distributions"): "Frequency distribution",
    ("math", 11, "Probability", "Axiomatic approach to probability"): "Probability axioms",
    ("math", 11, "Probability", "Addition theorem of probability"): "Probability axioms",

    # Class 12 Physics
    ("physics", 12, "Electrostatics", "Capacitors and dielectrics"): "Capacitor",
    ("physics", 12, "Magnetism and Matter", "Force on a moving charge and current-carrying conductor"): "Lorentz force",
    ("physics", 12, "Electromagnetic Induction and AC", "AC circuits (LCR)"): "RLC circuit",
    ("physics", 12, "Electromagnetic Induction and AC", "Transformers"): "Transformer",
    ("physics", 12, "Ray Optics and Optical Instruments", "Refraction at spherical surfaces"): "Refraction",
    ("physics", 12, "Ray Optics and Optical Instruments", "Combination of lenses and mirrors"): "Optical system",
    ("physics", 12, "Ray Optics and Optical Instruments", "Microscope and telescope"): "Optical microscope",
    ("physics", 12, "Wave Optics", "Diffraction and polarization"): "Diffraction",
    ("physics", 12, "Modern Physics", "Semiconductor diodes and logic gates"): "p–n junction",

    # Class 12 Math
    ("math", 12, "Relations, Functions and Inverse Trigonometry", "Types of functions"): "Function (mathematics)",
    ("math", 12, "Matrices and Determinants", "Solving linear equations using matrices"): "System of linear equations",
    ("math", 12, "Continuity, Differentiability and Applications of Derivatives", "Continuity and differentiability conditions"): "Continuous function",
    ("math", 12, "Continuity, Differentiability and Applications of Derivatives", "Rate of change and tangents/normals"): "Tangent",
    ("math", 12, "Integrals and Applications", "Area under curves"): "Integral",
    ("math", 12, "Differential Equations", "Formation of differential equations"): "Differential equation",
    ("math", 12, "Vectors and Three Dimensional Geometry", "Vector algebra and scalar/vector triple product"): "Triple product",
    ("math", 12, "Vectors and Three Dimensional Geometry", "Direction cosines and lines in 3D"): "Direction cosine",
    ("math", 12, "Probability", "Random variables and probability distributions"): "Probability distribution",
}
